<?php
// no direct file access
if (count(get_included_files()) == 1) header("Location: ../index.php", TRUE, 301);
?>
<!DOCTYPE HTML>
<!--
	Dopetones by HTML5 UP and noelli
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>

<head>
	<?php simplepagehead(); ?>
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<link rel="stylesheet" href="<?php echo TEMPLATE_DIR; ?>/assets/css/main.css" />
	<?php
	register_frontend_modfiles('css');
	register_frontend_modfiles('jquery');
	register_frontend_modfiles('js');

	$mainnav = show_menu2(
		$aMenu          = 1,
		$aStart         = SM2_ROOT,
		$aMaxLevel      = SM2_ALL,
		$aOptions       = SM2_ALL | SM2_PRETTY | SM2_BUFFER,
		$aItemOpen      = '<li [if (class==menu-current) { class="current" }]><a href="[url]" target="[target]">[menu_title]</a>',
		$aItemClose     = '</li>',
		$aMenuOpen      = '<ul>',
		$aMenuClose     = '</ul>',
		$aTopItemOpen   = false,
		$aTopMenuOpen   = '<ul>'
	);

	$footernav = show_menu2(
		$aMenu          = 2,
		$aStart         = SM2_ROOT,
		$aMaxLevel      = SM2_ALL,
		$aOptions       = SM2_ALL | SM2_PRETTY | SM2_BUFFER,
		$aItemOpen      = '<li><a href="[url]" target="[target]">[menu_title]</a>',
		$aItemClose     = '</li>',
		$aMenuOpen      = '<ul>',
		$aMenuClose     = '</ul>',
		$aTopItemOpen   = false,
		$aTopMenuOpen   = '<ul>'
	);

	require_once __DIR__ . '/info.php';
	foreach ($block as $k => $v) {
		ob_start();
		page_content($k);
		$block[$k] = ob_get_clean();
	}


	if (defined('MODULES_BLOCK2') and MODULES_BLOCK2 != '') {
		$block[2] .= MODULES_BLOCK2;
	}

	?>
</head>

<body class="p<?php echo PAGE_ID; ?> is-preload">
	<div id="page-wrapper">

		<!-- Header -->
		<section id="header">

			<!-- Logo -->
			<?php
			$logo_path_png = '/media/logo.png';

			 if (file_exists(WB_PATH . $logo_path_png)){
				echo '<div class="image"><a href="'  . WB_URL . '"><img src="' . WB_URL . $logo_path_png . '" alt="' . WEBSITE_TITLE . '""></a></div>';

			 } else {
				echo '<h1><a href="'  . WB_URL . '">' . WEBSITE_TITLE . '</a></h1>';
			 }
			?>

			<!-- Nav -->
			<nav id="nav">
				<?php echo $mainnav; ?>
			</nav>

			<?php if ($block[4] != '') { ?>
				<!-- Banner -->
				<section id="banner">
					<header>
						<?php echo $block[4]; ?>
					</header>
				</section>
			<?php } ?>

			<?php if ($block[5] != '') { ?>
				<!-- Intro -->
				<section id="intro" class="container">
					<div class="row">
						<?php echo $block[5]; ?>
					</div>
				</section>
			<?php } ?>
		</section>

		<!-- Main -->
		<section id="main">
			<div class="container">
				<?php
				$imp = ''; // needed when left column exists
				$col = ''; // needed when left or right column exists
				if ($block[2] != '' || $block[3] != '' || $block[20] != '' || $block[30] != '') {  // check if left or right column has content
					$col = 'col-8 col-12-medium'; // set width of main block
				?>
					<div class="row">
					<?php }
				// left sidebar
				if ($block[3] != '' || $block[30] != '') {
					$imp = 'imp-medium'; // set additional class for main block 
					?>
						<div class="col-4 col-12-medium">
							<?php
							// boxed sidebar
							if ($block[3] != '') { 	?>
								<section class="box">
									<?php echo $block[3]; ?>
								</section>
							<?php }
							// sidebar w/o box (boxes have to be generated by module)
							if ($block[30] != '') {
								echo $block[30];
							}
							?>
						</div>
					<?php }
				// main content with optional classes, otherwise just a div around 
					?>
					<div class="<?php echo $col . ' ' . $imp; ?>">

						<?php echo $block[1]; ?>

					</div>

					<?php
					// right sidebar
					if ($block[2] != '' || $block[20] != '') {
					?>
						<div class="col-4 col-12-medium">
							<?php
							// boxed sidebar
							if ($block[2] != '') { 	?>
								<section class="box">
									<?php echo $block[2]; ?>
								</section>
							<?php }
							// sidebar w/o box (boxes have to be generated by module)
							if ($block[20] != '') {
								echo $block[20];
							}
							?>
						</div>
					<?php
					}
					// close div if right or left sidebar exists
					if ($block[2] != '' || $block[3] != '' || $block[20] != '' || $block[30] != '') { ?>
					</div>
				<?php } ?>
			</div>
			<?php if ($block[6] != '') { ?>

				<section class="additional">
					<div class="container">
						<article class="box post">
							<?php echo $block[6]; ?>
						</article>
					</div>
				</section>
			<?php } ?>
		</section>


		<!-- Footer -->
		<section id="footer">

			<div class="container">
				<div class="row">
					<?php if ($block[7] != '') { ?>
						<div class="col-8 col-12-medium">
							<section>
								<?php echo $block[7]; ?>
							</section>
						</div>
					<?php }
					if ($block[8] != '') { ?>
						<div class="col-4 col-12-medium">
							<section>
								<?php echo $block[8]; ?>
							</section>
						</div>
					<?php }
					if ($block[9] != '') { ?>
						<div class="col-4 col-6-medium col-12-small">
							<section>
								<?php echo $block[9]; ?>
							</section>
						</div>
					<?php }
					if ($block[10] != '') { ?>
						<div class="col-4 col-6-medium col-12-small">
							<section>
								<?php echo $block[10]; ?>
							</section>
						</div>
					<?php }
					if ($block[11] != '') { ?>
						<div class="col-4 col-12-medium">
							<section>
								<?php echo $block[11]; ?>
							</section>
						</div>
					<?php } ?>
					<div class="col-6">
					<div id="bottomnav">
					<?php echo $mainnav; ?>
					</div>
					</div>
					<div class="col-6">
						<!-- Copyright -->
						<div id="copyright">
							<ul>
								<li>
									<?php
									echo WEBSITE_FOOTER;
									// do NOT remove the link to html5up unless you bought a license from them!!!
									?></li>
								<li>Theme: <a href="https://html5up.net" target="_blank" rel="noopener">HTML5 UP</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</section>

	</div>

	<!-- Scripts -->

	<script src="<?php echo TEMPLATE_DIR; ?>/assets/js/jquery.dropotron.min.js"></script>
	<script src="<?php echo TEMPLATE_DIR; ?>/assets/js/browser.min.js"></script>
	<script src="<?php echo TEMPLATE_DIR; ?>/assets/js/breakpoints.min.js"></script>
	<script src="<?php echo TEMPLATE_DIR; ?>/assets/js/util.js"></script>
	<script src="<?php echo TEMPLATE_DIR; ?>/assets/js/main.js"></script>

</body>

</html>